# Bilibili SponsorBlock 跳过插件
# 项目地址: https://github.com/bxy0128/bilibili-skipad

[rewrite_local]
# 拦截视频详情页请求提取 BVID，无需重写 Body，性能损耗最小
^https:\/\/app\.bilibili\.com\/x\/v2\/view\?.*bvid= url script-request-header https://raw.githubusercontent.com/bxy0128/bilibili-skipad/master/bilibiliadskip.js

[mitm]
hostname = app.bilibili.com
