[rewrite_local]
# 匹配 Wink 的两个核心用户信息接口
^https?:\/\/api-(wink\.meitumv|account\.meitu)\.com\/(user\/show|users\/show_current)\.json url script-response-body https://raw.githubusercontent.com/bxy0128/bilibili-skipad/master/bilibiliadskip.js

[mitm]
hostname = api-wink.meitumv.com, api.account.meitu.com
