[rewrite_local]
# 匹配 Wink 的两个核心用户信息接口
# 兼容 v3 和 api-cs 两个域名的匹配
^https?:\/\/(v3\.camscanner\.com|api-cs\.intsig\.net)\/.*query_?property url script-response-body https://raw.githubusercontent.com/bxy0128/bilibili-skipad/master/camscanner_v3.js
[mitm]
hostname = v3.camscanner.com, api-cs.intsig.net
